server:
  port: 19004

spring:
  application:
    name: 'generator_server'
  profiles:
    active: 'devp' #'home' #
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    default-property-inclusion: non_null
    locale: zh_CN
    time-zone: 'GMT+8'
  freemarker:
    template-loader-path: classpath:/templates
logging:
  level:
    com.liust: debug
  path: /Users/liust/log





